version: "3.4"

networks:
  vx-bridge:
    driver: bridge
  vx-external:
    external: true

services:
  app:
    build:
      context: .
    volumes:
      - ./:/var/app
    ports:
      - "9000:80"
    networks:
      - default
      - vx-external
      - vx-bridge
    depends_on:
      - database
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: laravel
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_DATABASE: laravel
    networks:
      - default


